# Generated by Django 5.1.6 on 2025-02-12 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_alter_serverstatus_options_serverstatus_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50, verbose_name='Параметр')),
                ('value', models.CharField(max_length=20, verbose_name='Значение')),
                ('start_time', models.DateTimeField(verbose_name='Время начала инцидента')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания инцидента')),
                ('resolved', models.BooleanField(default=False, verbose_name='Инцидент разрешён')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling.server', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
    ]
